name: Chalk test

on:
  push:
    branches: [ "develop"]
    paths-ignore:
     - target/**
     - dist/**
  # push:
  #   branches:
  #     - develop
  #   paths:
  #     - src/**
  #     - tests/**
  #     # ignore docs not to waste CI minutes
  #     - "!src/docs/**"

permissions:
  contents: read
  packages: write
jobs:
   Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3


      - name: Download Chalk Binary and check version
        run: |
          curl -fsSL "https://crashoverride.com/dl/chalk/chalk-0.2.2-$(uname -s)-$(uname -m)" > chalk && chmod +x chalk ./chalk version
        
