name: Chalk Analysis

on:
  push:
    branches: [ "develop"]

permissions:
  contents: read
  packages: write
jobs:
   Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: List the Repo Directories
        run: |
          ls -lart

      - name: Download Chalk Binary and check version
        run: |
          curl -fsSL "https://crashoverride.com/dl/chalk/chalk-0.2.2-$(uname -s)-$(uname -m)" > chalk && chmod +x chalk && ./chalk version
      - name: Do Chalk insert
        run: |
          ./chalk insert

      - name: Covert Chalk result to Json format
        run: |
          cat ~/.local/chalk/chalk.log > chalk_result.json

      - name: Display Chalk result
        run: |
          cat chalk_result.json

      - name: Upload json Report
        uses: actions/upload-artifact@v2
        with:
          name: chalk Result
          path: ./chalk_result.json

      - name: Download json Report
        uses: actions/download-artifact@v2
        with:
          name: chalk Result
          path: /Users/samir/Downloads/chalk_result.json
      

