name: Chalk Analysis

on:
  push:
    branches: [ "develop"]

permissions:
  contents: read
  packages: write
jobs:
   Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: List the Repo Directories
        run: |
          ls -lart

      - name: Download Chalk Binary and check version
        run: |
          curl -fsSL "https://crashoverride.com/dl/chalk/chalk-0.2.2-$(uname -s)-$(uname -m)" > chalk && chmod +x chalk && ./chalk version
      - name: Do Chalk insert
        run: |
          ./chalk insert

      - name: Display Chack result
        run: |
          vi ~/.local/chalk/chalk.log

